name: ESP32-S2

on:
  push:
    branches:
      - esp32s2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-latest]
        python-version: [3.7]
        example:
          - "examples/arduino-blink"
          - "examples/arduino-wifiscan"
          - "examples/espidf-arduino-blink"
          - "examples/espidf-arduino-wifiscan"
          - "examples/espidf-aws-iot"
          - "examples/espidf-coap-server"
          - "examples/espidf-exceptions"
          - "examples/espidf-hello-world"
          - "examples/espidf-http-request"
          - "examples/espidf-peripherals-uart"
          - "examples/espidf-peripherals-usb"
          - "examples/espidf-storage-sdcard"
          - "examples/espidf-storage-spiffs"
          - "examples/espidf-ulp-adc"
          - "examples/espidf-ulp-pulse"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          platformio platform install file://.
      - name: Build examples
        run: |
          platformio run -d ${{ matrix.example }}
